### ISSUE TITLE
Execution of custom oracle jobs

### ISSUE THREAD

**Issue by echevrier** [integritee-network/teeracle#16]
Everyone can request a custom oracle job to be executed on on a specific number of Teeracles.
See Requirements: https://github.com/integritee-network/teeracle/issues/15

The solution combines a teeracle pallet and one or more teeracles (integritee workers). It executes its core functionality as a trusted piece of code in an SGX enclave, which can attest that the blockchain is interacting with a legitimate, SGX-backed instance of the teeracle code.

**Note**: For now, we will limit our solution to a Rest API call and a JSON response.

1. **Request a simple custom oracle job on several Teeracles**

- [ ] Define a new type for custom query job :
* Custom query: URL & REST endpoint & query parameters & encrypted key if [paid]() API & encrypted user credentials if required
* JSON path to the desired object 
* Return Data Type. We will support all substrate and integritee Types. Length must be limited.
* Variable name for storage (Ex:"USD/TEER" for exchange rate)
* Request frequency (number of blocks between requests)
* Number of requests (ex: 10 times)
* Number of Teeracles that will execute the request

- [ ] Implement a generic teeracle pallet
* Design the generic teeracle pallet by taking into account specific teeracle pallet (ex: current teeracle pallet for exchange rate)
* The white list of oracles is no longer per data source but per features (code release for exchange_rate, generic teeracle, ...)  The verification of the data source is done with the certificate: See [2](https://github.com/integritee-network/teeracle/issues/16#:~:text=into%20supported%20types-,Authenticate%20sources%20with%20hard%2Dcoded%20certificates,-Solve%20%5Bteeracle%5D%20authenticate)  
* Make the request available for any user. Add a register-job call.
* Save the returned value on-chain. The returned value is characterized by a name, the data source, its type and a timestamp. The value can be saved only if it comes from a trusted oracle mrenclave: the enclave is registered and the  mrenclaves is in the whitelist.
* Choose in the available Teeracles which ones will execute the job : 
   * Random load balancing 
   * Add a custom job registry: job, Teeracles that will execute the job
* Add Events and Errors
* Update weights: Byte Fee?

- [ ] Implement the indirect invocation call for the request in the worker

- [ ] Implement a job-pool, where all jobs are stored
* Add a job
* Cancel a job
* Cache?
 
- [ ] Implement a job dispatcher:
* Decrypt the oracle job request (?)
* Dispatches oracle jobs from the pool
* Spawns a thread or new task for each job that is ready for execution
* Untrusted runtime spawns the dispatcher once on a separate thread on startup

- [ ] Implement a job-executor
* Call the query over Teeracle Rest Client
* Call the Wallet to create and send a signed extrinsic to the Teeracle pallet to save the value with a timestamp

- [ ] Implement a Teeracle Rest Client. The query result will be a JSON
* Get the json from the requested query
* Get the requested value in the json (json path to the value is submitted in the request)
* Convert the result, an untyped JSON Value into the requested type
* Throw error when something went wrong

- [ ] Implement a converter from untyped JSON Value into supported types
* support all substrate type
* support integritee type (ex: exchange rate)

- [ ] Clean when job is done
* Clean Teeracle Pallet : registry
* Clean job-pool

2. **Cancel a custom oracle job**
- [ ] In the generic teeracle pallet
* Add a cancel call
* Remove job from registry
* Cancel the job on the choosen Teeracles
* Add Events and Errors
- [ ] Implement the indirect invocation call in the worker and the cancel in the job dispatcher
- [ ] In the job-pool:
* cancel the job
* clean the schedule

3. **Authenticate sources with hard-coded certificates**

- [ ] Solve https://github.com/integritee-network/teeracle/issues/1
- [ ] Implement submission of the certificate by the user in the request 

4. **Enabling the request for private data**
Private data are submitted in the custom job request. They are encrypted by the user before sending the request using the teeracle shielding key. The user can get the shielding key over an RPC Getter 
- [ ] Im Teeracle job-dispatcher : 
* Decrypt the private data and add it to the query parameters before dispatching the request
      
5. **Manage subscription fee**

> **Teeracle tokenomics:**
> 
> - When a user requests the execution of a custom oracle task, a subscription fee is calculated and the corresponding amount reserved for the use of this service (in the user account). 
> - Subscription fee = fee for the delivery of the requested data (for the extrinsic) * number of teeracles that will execute the request * request frequency * duration. 
> -  The fee for a delivery is a fixed price : 
>        - Base Fee: amount for sending the extrinsic with the query result.
>        - Byte Fee: depending on the size of the query result. A maximum length has to be defined. 
> - The fee for a delivery are transferred to the Teeracle account that sends the extrinsic with the result. If a Teeracle fails to send the extrinsics after a defined period of time (timeout), the fee for a delivery is released to the user (unreserve). 
> - Automatic withdrawal of money from the Teeracle account to the beneficiary's account (Operator) : 
> The operator can define a beneficiary's account, a threshold and a withdrawal amount at start-up. As soon as the Teeracle account balance reaches the threshold, the withdrawal amount is transferred to the beneficiary's account.

- [ ] Implement subscription fee in Teeracle Pallet
* Compute the subscription fee 
* Save fee for a delivery in the job registry (?)
- [ ] Implement Fee payment 
* User transfer total fee into ? as a reserve balance 
* When query result is updated, fee for one query is transfer to the enclave account which sent the extrinsic
* When query failed, fee for one query is released to the user (unreserved)
* When a Teeracle is down, the pallet will release the fee for a delivery to the user after a timeout.
* When job is canceled remaining reserved balance released to the user (unreserved)

 6. **Operator withdraw**
- [ ] Implement a generic Payout Watchdog
* Watchdog subscribes to enclave balance
* Callback when enclave balance change -> check if total amount > threshold and transfer

**Comment by mosonyi** [comment]
Issue moved to [integritee-network/worker #1226](https://github.com/integritee-network/worker/issues/1226) via [**Zenhub**](https://www.zenhub.com/)
